bahrathkumaraju@Bahrathkumarajus-MacBook-Pro whatishelm % helm search repo stable/mysql --versions
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
stable/mysql            1.6.9           5.7.30          DEPRECATED - Fast, reliable, scalable, and easy...
stable/mysql            1.6.8           5.7.30          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.6.7           5.7.30          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.6.6           5.7.30          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.6.5           5.7.30          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.6.4           5.7.30          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.6.3           5.7.28          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.6.2           5.7.28          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.6.1           5.7.27          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.6.0           5.7.27          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.5.0           5.7.27          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.4.0           5.7.27          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.3.3           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.3.2           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.3.1           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.3.0           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.2.2           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.2.1           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.2.0           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.1.1           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.1.0           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            1.0.0           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.19.2          5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.19.1          5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.19.0          5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.17.0          5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.16.0          5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.15.0          5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.14.0          5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.13.3          5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.13.2          5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.13.1          5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.13.0          5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.12.0          5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.11.0          5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.10.2          5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.10.1          5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.10.0          5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.9.3           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.9.2           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.9.1           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.8.5           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.8.4           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.8.3           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.8.2           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.8.1           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.8.0           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.7.0           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.6.0           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.5.0           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.4.5           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.4.4           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.4.3           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.4.1           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.4.0           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.3.7           5.7.14          Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.3.6                           Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.3.5                           Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.3.4                           Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.3.3                           Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.3.2                           Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.3.1                           Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.3.0                           Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.2.9                           Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.2.8                           Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.2.7                           Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.2.6                           Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.2.5                           Fast, reliable, scalable, and easy to use open-...
stable/mysql            0.2.4                           Chart for MySQL                                   
stable/mysql            0.2.3                           Chart for MySQL                                   
stable/mysql            0.2.2                           Chart for MySQL                                   
stable/mysql            0.2.1                           Chart for MySQL                                   
stable/mysql            0.2.0                           Chart for MySQL                                   
stable/mysql            0.1.2                           Chart for MySQL                                   
stable/mysql            0.1.1                           Chart for MySQL                                   
stable/mysql            0.1.0                           Chart for MySQL                                   
stable/mysqldump        2.6.2           2.4.1           DEPRECATED! - A Helm chart to help backup MySQL...
stable/mysqldump        2.6.1           2.4.1           A Helm chart to help backup MySQL databases usi...
stable/mysqldump        2.6.0           2.4.1           A Helm chart to help backup MySQL databases usi...
stable/mysqldump        2.5.1           2.4.1           A Helm chart to help backup MySQL databases usi...
stable/mysqldump        2.5.0           2.4.1           A Helm chart to help backup MySQL databases usi...
stable/mysqldump        2.4.2           2.4.1           A Helm chart to help backup MySQL databases usi...
stable/mysqldump        2.4.1           2.4.1           A Helm chart to help backup MySQL databases usi...
stable/mysqldump        2.4.0           2.4.0           A Helm chart to help backup MySQL databases usi...
stable/mysqldump        2.3.1           2.3.1           A Helm chart to help backup MySQL databases usi...
stable/mysqldump        2.3.0           2.3.0           A Helm chart to help backup MySQL databases usi...
stable/mysqldump        2.2.0           2.2.0           A Helm chart to help backup MySQL databases usi...
stable/mysqldump        2.1.3           2.0.0           A Helm chart to help backup MySQL databases usi...
stable/mysqldump        2.1.2           2.0.0           A Helm chart to help backup MySQL databases usi...
stable/mysqldump        2.0.2           2.0.0           A Helm chart to help backup MySQL databases usi...
stable/mysqldump        2.0.1           2.0.0           A Helm chart to help backup MySQL databases usi...
stable/mysqldump        2.0.0           2.0.0           A Helm chart to help backup MySQL databases usi...
stable/mysqldump        1.0.0           5.7.21          A Helm chart to help backup MySQL databases usi...
stable/mysqldump        0.1.0           5.7.21          A Helm chart to help backup MySQL databases usi...
bahrathkumaraju@Bahrathkumarajus-MacBook-Pro whatishelm % 


bahrathkumaraju@Bahrathkumarajus-MacBook-Pro whatishelm % helm install mysql stable/mysql --version 1.6.8
NAME: mysql
LAST DEPLOYED: Fri Jun 10 08:31:32 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
MySQL can be accessed via port 3306 on the following DNS name from within your cluster:
mysql.default.svc.cluster.local

To get your root password run:

    MYSQL_ROOT_PASSWORD=$(kubectl get secret --namespace default mysql -o jsonpath="{.data.mysql-root-password}" | base64 --decode; echo)

To connect to your database:

1. Run an Ubuntu pod that you can use as a client:

    kubectl run -i --tty ubuntu --image=ubuntu:16.04 --restart=Never -- bash -il

2. Install the mysql client:

    $ apt-get update && apt-get install mysql-client -y

3. Connect using the mysql cli, then provide your password:
    $ mysql -h mysql -p

To connect to your database directly from outside the K8s cluster:
    MYSQL_HOST=127.0.0.1
    MYSQL_PORT=3306

    # Execute the following command to route the connection:
    kubectl port-forward svc/mysql 3306

    mysql -h ${MYSQL_HOST} -P${MYSQL_PORT} -u root -p${MYSQL_ROOT_PASSWORD}
bahrathkumaraju@Bahrathkumarajus-MacBook-Pro whatishelm %





bahrathkumaraju@Bahrathkumarajus-MacBook-Pro whatishelm % helm upgrade mysql stable/mysql --version 1.6.7
Release "mysql" has been upgraded. Happy Helming!
NAME: mysql
LAST DEPLOYED: Fri Jun 10 08:44:05 2022
NAMESPACE: default
STATUS: deployed
REVISION: 4
NOTES:
MySQL can be accessed via port 3306 on the following DNS name from within your cluster:
mysql.default.svc.cluster.local

To get your root password run:

    MYSQL_ROOT_PASSWORD=$(kubectl get secret --namespace default mysql -o jsonpath="{.data.mysql-root-password}" | base64 --decode; echo)

To connect to your database:

1. Run an Ubuntu pod that you can use as a client:

    kubectl run -i --tty ubuntu --image=ubuntu:16.04 --restart=Never -- bash -il

2. Install the mysql client:

    $ apt-get update && apt-get install mysql-client -y

3. Connect using the mysql cli, then provide your password:
    $ mysql -h mysql -p

To connect to your database directly from outside the K8s cluster:
    MYSQL_HOST=127.0.0.1
    MYSQL_PORT=3306

    # Execute the following command to route the connection:
    kubectl port-forward svc/mysql 3306

    mysql -h ${MYSQL_HOST} -P${MYSQL_PORT} -u root -p${MYSQL_ROOT_PASSWORD}
bahrathkumaraju@Bahrathkumarajus-MacBook-Pro whatishelm % helm repo list
NAME    URL                          
stable  https://charts.helm.sh/stable
bahrathkumaraju@Bahrathkumarajus-MacBook-Pro whatishelm % helm list     
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
mysql   default         4               2022-06-10 08:44:05.981161 +0800 +08    deployed        mysql-1.6.7     5.7.30     
bahrathkumaraju@Bahrathkumarajus-MacBook-Pro whatishelm % 



bahrathkumaraju@Bahrathkumarajus-MacBook-Pro whatishelm % helm history mysql
REVISION        UPDATED                         STATUS          CHART           APP VERSION     DESCRIPTION     
1               Fri Jun 10 08:42:56 2022        superseded      mysql-1.6.3     5.7.28          Install complete
2               Fri Jun 10 08:43:53 2022        superseded      mysql-1.6.3     5.7.28          Upgrade complete
3               Fri Jun 10 08:43:59 2022        superseded      mysql-1.6.5     5.7.30          Upgrade complete
4               Fri Jun 10 08:44:05 2022        deployed        mysql-1.6.7     5.7.30          Upgrade complete
bahrathkumaraju@Bahrathkumarajus-MacBook-Pro whatishelm % 



bahrathkumaraju@Bahrathkumarajus-MacBook-Pro whatishelm % kubectl get all
NAME                         READY   STATUS         RESTARTS   AGE
pod/mysql-7d99c88454-nskx9   0/1     ErrImagePull   0          3m33s

NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/kubernetes   ClusterIP   10.96.0.1        <none>        443/TCP    2d16h
service/mysql        ClusterIP   10.104.210.201   <none>        3306/TCP   4m51s

NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/mysql   0/1     1            0           4m51s

NAME                               DESIRED   CURRENT   READY   AGE
replicaset.apps/mysql-595fc8486b   0         0         0       4m51s
replicaset.apps/mysql-6f5bdc79d6   0         0         0       3m44s
replicaset.apps/mysql-7d99c88454   1         1         0       3m33s
bahrathkumaraju@Bahrathkumarajus-MacBook-Pro whatishelm % 


