apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ include "backend.fullname" . }}-ingress
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "backend.fullname" . }} 
            port: 
              number: 80

