apiVersion: v2
name: guestbook
appVersion: "2.0"
description: A Helm chart for Guestbook 2.0 
version: 1.0.0
type: application

dependencies:
  - name: backend
    version: ~0.1.0
    repository: http://localhost:8080
  - name: frontend
    version: ~1.1.0
    repository: http://localhost:8080
  - name: mongodb
    version: 12.1.x
    repository: https://charts.helm.sh/stable
#    repository: https://charts.bitnami.com/bitnami





