bahrathkumaraju@Bahrathkumarajus-MacBook-Pro whatishelm % helm search repo mongodb
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION                                       
bitnami/mongodb                         12.1.20         5.0.9           MongoDB(R) is a relational open source NoSQL da...
bitnami/mongodb-sharded                 5.0.12          5.0.9           MongoDB(R) is an open source NoSQL database tha...
stable/mongodb                          7.8.10          4.2.4           DEPRECATED NoSQL document-oriented database tha...
stable/mongodb-replicaset               3.17.2          3.6             DEPRECATED - NoSQL document-oriented database t...
stable/prometheus-mongodb-exporter      2.8.1           v0.10.0         DEPRECATED A Prometheus exporter for MongoDB me...
tyk-helm/simple-mongodb                 0.1.1                           A Simple Helm chart for running mongodb for CI    
chartmuseum/database                    0.1.0           3.6             A helm chart for Guestbook Database Mongodb 3.6   
tyk-helm/tyk-headless                   0.9.0           1.0             Deploys Tyk Gateway, assumes that MongoDB and R...
tyk-helm/tyk-pro                        0.9.0           1.0             Deploys Tyk Dashboard, assumes that MongoDB and...
stable/unifi                            0.10.2          5.12.35         DEPRECATED - Ubiquiti Network's Unifi Controller  
bahrathkumaraju@Bahrathkumarajus-MacBook-Pro whatishelm % 

