apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
spec:
  rules:
{{- range .Values.ingress.hosts }}
      - host: {{ .hostname | quote }}
        http:
          paths:
          {{- range.paths }}
            - path: {{ .path }}
              pathType: prefix
              backend:
                service:
                  name:  {{ .service }}
          {{- end }}
{{ end -}}
  
