config:
  guestbook_name: "MyPopRock Festival 2.0"
  backend_uri: "http://backend.minikube.local/guestbook"
replicaCount: 1
image:
  repository: phico/frontend
  tag: "2.0"
service:
  port: 80
  type: ClusterIP
ingress:
  host: forntend.minikube.local



